# Generated by Django 5.2.5 on 2026-08-16 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('join_code', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=128)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='syncapi.household')),
            ],
        ),
        migrations.CreateModel(
            name='SyncEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('client_updated_at', models.DateTimeField()),
                ('winning_operation_id', models.CharField(max_length=128)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='syncapi.household')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('version', models.PositiveBigIntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='syncapi.household')),
                ('sync_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncapi.syncentity')),
            ],
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('operation_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('accepted', models.BooleanField()),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncapi.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='syncapi.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('household', 'user'), name='unique_household_member')],
            },
        ),
        migrations.AddConstraint(
            model_name='syncentity',
            constraint=models.UniqueConstraint(fields=('household', 'entity_type', 'entity_id'), name='unique_synced_entity'),
        ),
    ]
