import React, { useEffect, useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ScrollView, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useGroup } from '@/context/GroupContext';
import { GroupRepository } from '@/database/repositories/GroupRepository';
import { COLORS } from '@/utils/constants';
import { useNavigation } from '@react-navigation/native';

export default function GroupSettingsScreen() {
  const { activeGroup, activeGroupId, refreshActiveGroup } = useGroup(); const navigation = useNavigation();
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [currency, setCurrency] = useState('BDT'); const [saving, setSaving] = useState(false);
  useEffect(() => { setName(activeGroup?.name || ''); setDescription(activeGroup?.description || ''); setCurrency(activeGroup?.currency || 'BDT'); }, [activeGroup]);
  async function handleSave() { if (!activeGroupId || !activeGroup) return; setSaving(true); await GroupRepository.upsert({ ...activeGroup, name: name.trim() || activeGroup.name, description: description.trim(), currency: currency.trim().toUpperCase() || 'BDT', updated_date: new Date().toISOString() }); await refreshActiveGroup(); setSaving(false); Alert.alert('Saved', 'Local household settings updated.'); }
  return <SafeAreaView style={styles.container}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.backButton}>‹ Back</Text></TouchableOpacity><Text style={styles.title}>Household settings</Text></View><ScrollView contentContainerStyle={styles.content}><View style={styles.card}><Text style={styles.sectionTitle}>Stored only on this device</Text><Text style={styles.inputLabel}>Name</Text><TextInput style={styles.input} value={name} onChangeText={setName} /><Text style={styles.inputLabel}>Description</Text><TextInput style={[styles.input, styles.textArea]} value={description} onChangeText={setDescription} multiline /><Text style={styles.inputLabel}>Currency code</Text><TextInput style={styles.input} value={currency} onChangeText={setCurrency} autoCapitalize="characters" maxLength={3} /></View><TouchableOpacity style={styles.saveButton} onPress={handleSave} disabled={saving}><Text style={styles.saveButtonText}>{saving ? 'Saving...' : 'Save changes'}</Text></TouchableOpacity></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.BACKGROUND }, header: { flexDirection: 'row', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: COLORS.BORDER, backgroundColor: COLORS.CARD }, backButton: { fontSize: 16, color: COLORS.PRIMARY_DARK, fontWeight: '600' }, title: { fontSize: 20, fontWeight: '700', color: COLORS.TEXT, marginLeft: 12 }, content: { padding: 16 }, card: { backgroundColor: COLORS.CARD, borderRadius: 12, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: COLORS.BORDER }, sectionTitle: { fontSize: 16, fontWeight: '700', color: COLORS.TEXT, marginBottom: 14 }, inputLabel: { fontSize: 13, color: COLORS.TEXT_MUTED, fontWeight: '600', marginBottom: 6 }, input: { borderWidth: 1, borderColor: COLORS.BORDER, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, marginBottom: 10, backgroundColor: COLORS.BACKGROUND, color: COLORS.TEXT }, textArea: { minHeight: 80, textAlignVertical: 'top' }, saveButton: { backgroundColor: COLORS.PRIMARY_DARK, borderRadius: 10, paddingVertical: 15, alignItems: 'center' }, saveButtonText: { color: COLORS.WHITE, fontSize: 16, fontWeight: '700' } });
